
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1Choice ( Name = "AdditionalService_Response") ]
    public class AdditionalService_Response : IASN1PreparedElement {
                    
        
	private VMDStop_Response vMDStop_ ;
        private bool  vMDStop_selected = false ;
        
                
        
        [ASN1Element ( Name = "vMDStop", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public VMDStop_Response VMDStop
        {
            get { return vMDStop_; }
            set { selectVMDStop(value); }
        }
        
                
          
        
	private VMDReset_Response vMDReset_ ;
        private bool  vMDReset_selected = false ;
        
                
        
        [ASN1Element ( Name = "vMDReset", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public VMDReset_Response VMDReset
        {
            get { return vMDReset_; }
            set { selectVMDReset(value); }
        }
        
                
          
        
	private Select_Response select_ ;
        private bool  select_selected = false ;
        
                
        
        [ASN1Element ( Name = "select", IsOptional =  false , HasTag =  true, Tag = 2 , HasDefaultValue =  false )  ]
    
        public Select_Response Select
        {
            get { return select_; }
            set { selectSelect(value); }
        }
        
                
          
        
	private AlterProgramInvocationAttributes_Response alterPI_ ;
        private bool  alterPI_selected = false ;
        
                
        
        [ASN1Element ( Name = "alterPI", IsOptional =  false , HasTag =  true, Tag = 3 , HasDefaultValue =  false )  ]
    
        public AlterProgramInvocationAttributes_Response AlterPI
        {
            get { return alterPI_; }
            set { selectAlterPI(value); }
        }
        
                
          
        
	private InitiateUnitControlLoad_Response initiateUCLoad_ ;
        private bool  initiateUCLoad_selected = false ;
        
                
        
        [ASN1Element ( Name = "initiateUCLoad", IsOptional =  false , HasTag =  true, Tag = 4 , HasDefaultValue =  false )  ]
    
        public InitiateUnitControlLoad_Response InitiateUCLoad
        {
            get { return initiateUCLoad_; }
            set { selectInitiateUCLoad(value); }
        }
        
                
          
        
	private UnitControlLoadSegment_Response uCLoad_ ;
        private bool  uCLoad_selected = false ;
        
                
        
        [ASN1Element ( Name = "uCLoad", IsOptional =  false , HasTag =  true, Tag = 5 , HasDefaultValue =  false )  ]
    
        public UnitControlLoadSegment_Response UCLoad
        {
            get { return uCLoad_; }
            set { selectUCLoad(value); }
        }
        
                
          
        
	private UnitControlUpload_Response uCUpload_ ;
        private bool  uCUpload_selected = false ;
        
                
        
        [ASN1Element ( Name = "uCUpload", IsOptional =  false , HasTag =  true, Tag = 6 , HasDefaultValue =  false )  ]
    
        public UnitControlUpload_Response UCUpload
        {
            get { return uCUpload_; }
            set { selectUCUpload(value); }
        }
        
                
          
        
	private StartUnitControl_Response startUC_ ;
        private bool  startUC_selected = false ;
        
                
        
        [ASN1Element ( Name = "startUC", IsOptional =  false , HasTag =  true, Tag = 7 , HasDefaultValue =  false )  ]
    
        public StartUnitControl_Response StartUC
        {
            get { return startUC_; }
            set { selectStartUC(value); }
        }
        
                
          
        
	private StopUnitControl_Response stopUC_ ;
        private bool  stopUC_selected = false ;
        
                
        
        [ASN1Element ( Name = "stopUC", IsOptional =  false , HasTag =  true, Tag = 8 , HasDefaultValue =  false )  ]
    
        public StopUnitControl_Response StopUC
        {
            get { return stopUC_; }
            set { selectStopUC(value); }
        }
        
                
          
        
	private CreateUnitControl_Response createUC_ ;
        private bool  createUC_selected = false ;
        
                
        
        [ASN1Element ( Name = "createUC", IsOptional =  false , HasTag =  true, Tag = 9 , HasDefaultValue =  false )  ]
    
        public CreateUnitControl_Response CreateUC
        {
            get { return createUC_; }
            set { selectCreateUC(value); }
        }
        
                
          
        
	private AddToUnitControl_Response addToUC_ ;
        private bool  addToUC_selected = false ;
        
                
        
        [ASN1Element ( Name = "addToUC", IsOptional =  false , HasTag =  true, Tag = 10 , HasDefaultValue =  false )  ]
    
        public AddToUnitControl_Response AddToUC
        {
            get { return addToUC_; }
            set { selectAddToUC(value); }
        }
        
                
          
        
	private RemoveFromUnitControl_Response removeFromUC_ ;
        private bool  removeFromUC_selected = false ;
        
                
        
        [ASN1Element ( Name = "removeFromUC", IsOptional =  false , HasTag =  true, Tag = 11 , HasDefaultValue =  false )  ]
    
        public RemoveFromUnitControl_Response RemoveFromUC
        {
            get { return removeFromUC_; }
            set { selectRemoveFromUC(value); }
        }
        
                
          
        
	private GetUnitControlAttributes_Response getUCAttributes_ ;
        private bool  getUCAttributes_selected = false ;
        
                
        
        [ASN1Element ( Name = "getUCAttributes", IsOptional =  false , HasTag =  true, Tag = 12 , HasDefaultValue =  false )  ]
    
        public GetUnitControlAttributes_Response GetUCAttributes
        {
            get { return getUCAttributes_; }
            set { selectGetUCAttributes(value); }
        }
        
                
          
        
	private LoadUnitControlFromFile_Response loadUCFromFile_ ;
        private bool  loadUCFromFile_selected = false ;
        
                
        
        [ASN1Element ( Name = "loadUCFromFile", IsOptional =  false , HasTag =  true, Tag = 13 , HasDefaultValue =  false )  ]
    
        public LoadUnitControlFromFile_Response LoadUCFromFile
        {
            get { return loadUCFromFile_; }
            set { selectLoadUCFromFile(value); }
        }
        
                
          
        
	private StoreUnitControlToFile_Response storeUCToFile_ ;
        private bool  storeUCToFile_selected = false ;
        
                
        
        [ASN1Element ( Name = "storeUCToFile", IsOptional =  false , HasTag =  true, Tag = 14 , HasDefaultValue =  false )  ]
    
        public StoreUnitControlToFile_Response StoreUCToFile
        {
            get { return storeUCToFile_; }
            set { selectStoreUCToFile(value); }
        }
        
                
          
        
	private DeleteUnitControl_Response deleteUC_ ;
        private bool  deleteUC_selected = false ;
        
                
        
        [ASN1Element ( Name = "deleteUC", IsOptional =  false , HasTag =  true, Tag = 15 , HasDefaultValue =  false )  ]
    
        public DeleteUnitControl_Response DeleteUC
        {
            get { return deleteUC_; }
            set { selectDeleteUC(value); }
        }
        
                
          
        
	private DefineEventConditionList_Response defineECL_ ;
        private bool  defineECL_selected = false ;
        
                
        
        [ASN1Element ( Name = "defineECL", IsOptional =  false , HasTag =  true, Tag = 16 , HasDefaultValue =  false )  ]
    
        public DefineEventConditionList_Response DefineECL
        {
            get { return defineECL_; }
            set { selectDefineECL(value); }
        }
        
                
          
        
	private DeleteEventConditionList_Response deleteECL_ ;
        private bool  deleteECL_selected = false ;
        
                
        
        [ASN1Element ( Name = "deleteECL", IsOptional =  false , HasTag =  true, Tag = 17 , HasDefaultValue =  false )  ]
    
        public DeleteEventConditionList_Response DeleteECL
        {
            get { return deleteECL_; }
            set { selectDeleteECL(value); }
        }
        
                
          
        
	private AddEventConditionListReference_Response addECLReference_ ;
        private bool  addECLReference_selected = false ;
        
                
        
        [ASN1Element ( Name = "addECLReference", IsOptional =  false , HasTag =  true, Tag = 18 , HasDefaultValue =  false )  ]
    
        public AddEventConditionListReference_Response AddECLReference
        {
            get { return addECLReference_; }
            set { selectAddECLReference(value); }
        }
        
                
          
        
	private RemoveEventConditionListReference_Response removeECLReference_ ;
        private bool  removeECLReference_selected = false ;
        
                
        
        [ASN1Element ( Name = "removeECLReference", IsOptional =  false , HasTag =  true, Tag = 19 , HasDefaultValue =  false )  ]
    
        public RemoveEventConditionListReference_Response RemoveECLReference
        {
            get { return removeECLReference_; }
            set { selectRemoveECLReference(value); }
        }
        
                
          
        
	private GetEventConditionListAttributes_Response getECLAttributes_ ;
        private bool  getECLAttributes_selected = false ;
        
                
        
        [ASN1Element ( Name = "getECLAttributes", IsOptional =  false , HasTag =  true, Tag = 20 , HasDefaultValue =  false )  ]
    
        public GetEventConditionListAttributes_Response GetECLAttributes
        {
            get { return getECLAttributes_; }
            set { selectGetECLAttributes(value); }
        }
        
                
          
        
	private ReportEventConditionListStatus_Response reportECLStatus_ ;
        private bool  reportECLStatus_selected = false ;
        
                
        
        [ASN1Element ( Name = "reportECLStatus", IsOptional =  false , HasTag =  true, Tag = 21 , HasDefaultValue =  false )  ]
    
        public ReportEventConditionListStatus_Response ReportECLStatus
        {
            get { return reportECLStatus_; }
            set { selectReportECLStatus(value); }
        }
        
                
          
        
	private AlterEventConditionListMonitoring_Response alterECLMonitoring_ ;
        private bool  alterECLMonitoring_selected = false ;
        
                
        
        [ASN1Element ( Name = "alterECLMonitoring", IsOptional =  false , HasTag =  true, Tag = 22 , HasDefaultValue =  false )  ]
    
        public AlterEventConditionListMonitoring_Response AlterECLMonitoring
        {
            get { return alterECLMonitoring_; }
            set { selectAlterECLMonitoring(value); }
        }
        
                
          
        public bool isVMDStopSelected () {
            return this.vMDStop_selected ;
        }

        


        public void selectVMDStop (VMDStop_Response val) {
            this.vMDStop_ = val;
            this.vMDStop_selected = true;
            
            
                    this.vMDReset_selected = false;
                
                    this.select_selected = false;
                
                    this.alterPI_selected = false;
                
                    this.initiateUCLoad_selected = false;
                
                    this.uCLoad_selected = false;
                
                    this.uCUpload_selected = false;
                
                    this.startUC_selected = false;
                
                    this.stopUC_selected = false;
                
                    this.createUC_selected = false;
                
                    this.addToUC_selected = false;
                
                    this.removeFromUC_selected = false;
                
                    this.getUCAttributes_selected = false;
                
                    this.loadUCFromFile_selected = false;
                
                    this.storeUCToFile_selected = false;
                
                    this.deleteUC_selected = false;
                
                    this.defineECL_selected = false;
                
                    this.deleteECL_selected = false;
                
                    this.addECLReference_selected = false;
                
                    this.removeECLReference_selected = false;
                
                    this.getECLAttributes_selected = false;
                
                    this.reportECLStatus_selected = false;
                
                    this.alterECLMonitoring_selected = false;
                            
        }
        
          
        public bool isVMDResetSelected () {
            return this.vMDReset_selected ;
        }

        


        public void selectVMDReset (VMDReset_Response val) {
            this.vMDReset_ = val;
            this.vMDReset_selected = true;
            
            
                    this.vMDStop_selected = false;
                
                    this.select_selected = false;
                
                    this.alterPI_selected = false;
                
                    this.initiateUCLoad_selected = false;
                
                    this.uCLoad_selected = false;
                
                    this.uCUpload_selected = false;
                
                    this.startUC_selected = false;
                
                    this.stopUC_selected = false;
                
                    this.createUC_selected = false;
                
                    this.addToUC_selected = false;
                
                    this.removeFromUC_selected = false;
                
                    this.getUCAttributes_selected = false;
                
                    this.loadUCFromFile_selected = false;
                
                    this.storeUCToFile_selected = false;
                
                    this.deleteUC_selected = false;
                
                    this.defineECL_selected = false;
                
                    this.deleteECL_selected = false;
                
                    this.addECLReference_selected = false;
                
                    this.removeECLReference_selected = false;
                
                    this.getECLAttributes_selected = false;
                
                    this.reportECLStatus_selected = false;
                
                    this.alterECLMonitoring_selected = false;
                            
        }
        
          
        public bool isSelectSelected () {
            return this.select_selected ;
        }

        


        public void selectSelect (Select_Response val) {
            this.select_ = val;
            this.select_selected = true;
            
            
                    this.vMDStop_selected = false;
                
                    this.vMDReset_selected = false;
                
                    this.alterPI_selected = false;
                
                    this.initiateUCLoad_selected = false;
                
                    this.uCLoad_selected = false;
                
                    this.uCUpload_selected = false;
                
                    this.startUC_selected = false;
                
                    this.stopUC_selected = false;
                
                    this.createUC_selected = false;
                
                    this.addToUC_selected = false;
                
                    this.removeFromUC_selected = false;
                
                    this.getUCAttributes_selected = false;
                
                    this.loadUCFromFile_selected = false;
                
                    this.storeUCToFile_selected = false;
                
                    this.deleteUC_selected = false;
                
                    this.defineECL_selected = false;
                
                    this.deleteECL_selected = false;
                
                    this.addECLReference_selected = false;
                
                    this.removeECLReference_selected = false;
                
                    this.getECLAttributes_selected = false;
                
                    this.reportECLStatus_selected = false;
                
                    this.alterECLMonitoring_selected = false;
                            
        }
        
          
        public bool isAlterPISelected () {
            return this.alterPI_selected ;
        }

        


        public void selectAlterPI (AlterProgramInvocationAttributes_Response val) {
            this.alterPI_ = val;
            this.alterPI_selected = true;
            
            
                    this.vMDStop_selected = false;
                
                    this.vMDReset_selected = false;
                
                    this.select_selected = false;
                
                    this.initiateUCLoad_selected = false;
                
                    this.uCLoad_selected = false;
                
                    this.uCUpload_selected = false;
                
                    this.startUC_selected = false;
                
                    this.stopUC_selected = false;
                
                    this.createUC_selected = false;
                
                    this.addToUC_selected = false;
                
                    this.removeFromUC_selected = false;
                
                    this.getUCAttributes_selected = false;
                
                    this.loadUCFromFile_selected = false;
                
                    this.storeUCToFile_selected = false;
                
                    this.deleteUC_selected = false;
                
                    this.defineECL_selected = false;
                
                    this.deleteECL_selected = false;
                
                    this.addECLReference_selected = false;
                
                    this.removeECLReference_selected = false;
                
                    this.getECLAttributes_selected = false;
                
                    this.reportECLStatus_selected = false;
                
                    this.alterECLMonitoring_selected = false;
                            
        }
        
          
        public bool isInitiateUCLoadSelected () {
            return this.initiateUCLoad_selected ;
        }

        


        public void selectInitiateUCLoad (InitiateUnitControlLoad_Response val) {
            this.initiateUCLoad_ = val;
            this.initiateUCLoad_selected = true;
            
            
                    this.vMDStop_selected = false;
                
                    this.vMDReset_selected = false;
                
                    this.select_selected = false;
                
                    this.alterPI_selected = false;
                
                    this.uCLoad_selected = false;
                
                    this.uCUpload_selected = false;
                
                    this.startUC_selected = false;
                
                    this.stopUC_selected = false;
                
                    this.createUC_selected = false;
                
                    this.addToUC_selected = false;
                
                    this.removeFromUC_selected = false;
                
                    this.getUCAttributes_selected = false;
                
                    this.loadUCFromFile_selected = false;
                
                    this.storeUCToFile_selected = false;
                
                    this.deleteUC_selected = false;
                
                    this.defineECL_selected = false;
                
                    this.deleteECL_selected = false;
                
                    this.addECLReference_selected = false;
                
                    this.removeECLReference_selected = false;
                
                    this.getECLAttributes_selected = false;
                
                    this.reportECLStatus_selected = false;
                
                    this.alterECLMonitoring_selected = false;
                            
        }
        
          
        public bool isUCLoadSelected () {
            return this.uCLoad_selected ;
        }

        


        public void selectUCLoad (UnitControlLoadSegment_Response val) {
            this.uCLoad_ = val;
            this.uCLoad_selected = true;
            
            
                    this.vMDStop_selected = false;
                
                    this.vMDReset_selected = false;
                
                    this.select_selected = false;
                
                    this.alterPI_selected = false;
                
                    this.initiateUCLoad_selected = false;
                
                    this.uCUpload_selected = false;
                
                    this.startUC_selected = false;
                
                    this.stopUC_selected = false;
                
                    this.createUC_selected = false;
                
                    this.addToUC_selected = false;
                
                    this.removeFromUC_selected = false;
                
                    this.getUCAttributes_selected = false;
                
                    this.loadUCFromFile_selected = false;
                
                    this.storeUCToFile_selected = false;
                
                    this.deleteUC_selected = false;
                
                    this.defineECL_selected = false;
                
                    this.deleteECL_selected = false;
                
                    this.addECLReference_selected = false;
                
                    this.removeECLReference_selected = false;
                
                    this.getECLAttributes_selected = false;
                
                    this.reportECLStatus_selected = false;
                
                    this.alterECLMonitoring_selected = false;
                            
        }
        
          
        public bool isUCUploadSelected () {
            return this.uCUpload_selected ;
        }

        


        public void selectUCUpload (UnitControlUpload_Response val) {
            this.uCUpload_ = val;
            this.uCUpload_selected = true;
            
            
                    this.vMDStop_selected = false;
                
                    this.vMDReset_selected = false;
                
                    this.select_selected = false;
                
                    this.alterPI_selected = false;
                
                    this.initiateUCLoad_selected = false;
                
                    this.uCLoad_selected = false;
                
                    this.startUC_selected = false;
                
                    this.stopUC_selected = false;
                
                    this.createUC_selected = false;
                
                    this.addToUC_selected = false;
                
                    this.removeFromUC_selected = false;
                
                    this.getUCAttributes_selected = false;
                
                    this.loadUCFromFile_selected = false;
                
                    this.storeUCToFile_selected = false;
                
                    this.deleteUC_selected = false;
                
                    this.defineECL_selected = false;
                
                    this.deleteECL_selected = false;
                
                    this.addECLReference_selected = false;
                
                    this.removeECLReference_selected = false;
                
                    this.getECLAttributes_selected = false;
                
                    this.reportECLStatus_selected = false;
                
                    this.alterECLMonitoring_selected = false;
                            
        }
        
          
        public bool isStartUCSelected () {
            return this.startUC_selected ;
        }

        


        public void selectStartUC (StartUnitControl_Response val) {
            this.startUC_ = val;
            this.startUC_selected = true;
            
            
                    this.vMDStop_selected = false;
                
                    this.vMDReset_selected = false;
                
                    this.select_selected = false;
                
                    this.alterPI_selected = false;
                
                    this.initiateUCLoad_selected = false;
                
                    this.uCLoad_selected = false;
                
                    this.uCUpload_selected = false;
                
                    this.stopUC_selected = false;
                
                    this.createUC_selected = false;
                
                    this.addToUC_selected = false;
                
                    this.removeFromUC_selected = false;
                
                    this.getUCAttributes_selected = false;
                
                    this.loadUCFromFile_selected = false;
                
                    this.storeUCToFile_selected = false;
                
                    this.deleteUC_selected = false;
                
                    this.defineECL_selected = false;
                
                    this.deleteECL_selected = false;
                
                    this.addECLReference_selected = false;
                
                    this.removeECLReference_selected = false;
                
                    this.getECLAttributes_selected = false;
                
                    this.reportECLStatus_selected = false;
                
                    this.alterECLMonitoring_selected = false;
                            
        }
        
          
        public bool isStopUCSelected () {
            return this.stopUC_selected ;
        }

        


        public void selectStopUC (StopUnitControl_Response val) {
            this.stopUC_ = val;
            this.stopUC_selected = true;
            
            
                    this.vMDStop_selected = false;
                
                    this.vMDReset_selected = false;
                
                    this.select_selected = false;
                
                    this.alterPI_selected = false;
                
                    this.initiateUCLoad_selected = false;
                
                    this.uCLoad_selected = false;
                
                    this.uCUpload_selected = false;
                
                    this.startUC_selected = false;
                
                    this.createUC_selected = false;
                
                    this.addToUC_selected = false;
                
                    this.removeFromUC_selected = false;
                
                    this.getUCAttributes_selected = false;
                
                    this.loadUCFromFile_selected = false;
                
                    this.storeUCToFile_selected = false;
                
                    this.deleteUC_selected = false;
                
                    this.defineECL_selected = false;
                
                    this.deleteECL_selected = false;
                
                    this.addECLReference_selected = false;
                
                    this.removeECLReference_selected = false;
                
                    this.getECLAttributes_selected = false;
                
                    this.reportECLStatus_selected = false;
                
                    this.alterECLMonitoring_selected = false;
                            
        }
        
          
        public bool isCreateUCSelected () {
            return this.createUC_selected ;
        }

        


        public void selectCreateUC (CreateUnitControl_Response val) {
            this.createUC_ = val;
            this.createUC_selected = true;
            
            
                    this.vMDStop_selected = false;
                
                    this.vMDReset_selected = false;
                
                    this.select_selected = false;
                
                    this.alterPI_selected = false;
                
                    this.initiateUCLoad_selected = false;
                
                    this.uCLoad_selected = false;
                
                    this.uCUpload_selected = false;
                
                    this.startUC_selected = false;
                
                    this.stopUC_selected = false;
                
                    this.addToUC_selected = false;
                
                    this.removeFromUC_selected = false;
                
                    this.getUCAttributes_selected = false;
                
                    this.loadUCFromFile_selected = false;
                
                    this.storeUCToFile_selected = false;
                
                    this.deleteUC_selected = false;
                
                    this.defineECL_selected = false;
                
                    this.deleteECL_selected = false;
                
                    this.addECLReference_selected = false;
                
                    this.removeECLReference_selected = false;
                
                    this.getECLAttributes_selected = false;
                
                    this.reportECLStatus_selected = false;
                
                    this.alterECLMonitoring_selected = false;
                            
        }
        
          
        public bool isAddToUCSelected () {
            return this.addToUC_selected ;
        }

        


        public void selectAddToUC (AddToUnitControl_Response val) {
            this.addToUC_ = val;
            this.addToUC_selected = true;
            
            
                    this.vMDStop_selected = false;
                
                    this.vMDReset_selected = false;
                
                    this.select_selected = false;
                
                    this.alterPI_selected = false;
                
                    this.initiateUCLoad_selected = false;
                
                    this.uCLoad_selected = false;
                
                    this.uCUpload_selected = false;
                
                    this.startUC_selected = false;
                
                    this.stopUC_selected = false;
                
                    this.createUC_selected = false;
                
                    this.removeFromUC_selected = false;
                
                    this.getUCAttributes_selected = false;
                
                    this.loadUCFromFile_selected = false;
                
                    this.storeUCToFile_selected = false;
                
                    this.deleteUC_selected = false;
                
                    this.defineECL_selected = false;
                
                    this.deleteECL_selected = false;
                
                    this.addECLReference_selected = false;
                
                    this.removeECLReference_selected = false;
                
                    this.getECLAttributes_selected = false;
                
                    this.reportECLStatus_selected = false;
                
                    this.alterECLMonitoring_selected = false;
                            
        }
        
          
        public bool isRemoveFromUCSelected () {
            return this.removeFromUC_selected ;
        }

        


        public void selectRemoveFromUC (RemoveFromUnitControl_Response val) {
            this.removeFromUC_ = val;
            this.removeFromUC_selected = true;
            
            
                    this.vMDStop_selected = false;
                
                    this.vMDReset_selected = false;
                
                    this.select_selected = false;
                
                    this.alterPI_selected = false;
                
                    this.initiateUCLoad_selected = false;
                
                    this.uCLoad_selected = false;
                
                    this.uCUpload_selected = false;
                
                    this.startUC_selected = false;
                
                    this.stopUC_selected = false;
                
                    this.createUC_selected = false;
                
                    this.addToUC_selected = false;
                
                    this.getUCAttributes_selected = false;
                
                    this.loadUCFromFile_selected = false;
                
                    this.storeUCToFile_selected = false;
                
                    this.deleteUC_selected = false;
                
                    this.defineECL_selected = false;
                
                    this.deleteECL_selected = false;
                
                    this.addECLReference_selected = false;
                
                    this.removeECLReference_selected = false;
                
                    this.getECLAttributes_selected = false;
                
                    this.reportECLStatus_selected = false;
                
                    this.alterECLMonitoring_selected = false;
                            
        }
        
          
        public bool isGetUCAttributesSelected () {
            return this.getUCAttributes_selected ;
        }

        


        public void selectGetUCAttributes (GetUnitControlAttributes_Response val) {
            this.getUCAttributes_ = val;
            this.getUCAttributes_selected = true;
            
            
                    this.vMDStop_selected = false;
                
                    this.vMDReset_selected = false;
                
                    this.select_selected = false;
                
                    this.alterPI_selected = false;
                
                    this.initiateUCLoad_selected = false;
                
                    this.uCLoad_selected = false;
                
                    this.uCUpload_selected = false;
                
                    this.startUC_selected = false;
                
                    this.stopUC_selected = false;
                
                    this.createUC_selected = false;
                
                    this.addToUC_selected = false;
                
                    this.removeFromUC_selected = false;
                
                    this.loadUCFromFile_selected = false;
                
                    this.storeUCToFile_selected = false;
                
                    this.deleteUC_selected = false;
                
                    this.defineECL_selected = false;
                
                    this.deleteECL_selected = false;
                
                    this.addECLReference_selected = false;
                
                    this.removeECLReference_selected = false;
                
                    this.getECLAttributes_selected = false;
                
                    this.reportECLStatus_selected = false;
                
                    this.alterECLMonitoring_selected = false;
                            
        }
        
          
        public bool isLoadUCFromFileSelected () {
            return this.loadUCFromFile_selected ;
        }

        


        public void selectLoadUCFromFile (LoadUnitControlFromFile_Response val) {
            this.loadUCFromFile_ = val;
            this.loadUCFromFile_selected = true;
            
            
                    this.vMDStop_selected = false;
                
                    this.vMDReset_selected = false;
                
                    this.select_selected = false;
                
                    this.alterPI_selected = false;
                
                    this.initiateUCLoad_selected = false;
                
                    this.uCLoad_selected = false;
                
                    this.uCUpload_selected = false;
                
                    this.startUC_selected = false;
                
                    this.stopUC_selected = false;
                
                    this.createUC_selected = false;
                
                    this.addToUC_selected = false;
                
                    this.removeFromUC_selected = false;
                
                    this.getUCAttributes_selected = false;
                
                    this.storeUCToFile_selected = false;
                
                    this.deleteUC_selected = false;
                
                    this.defineECL_selected = false;
                
                    this.deleteECL_selected = false;
                
                    this.addECLReference_selected = false;
                
                    this.removeECLReference_selected = false;
                
                    this.getECLAttributes_selected = false;
                
                    this.reportECLStatus_selected = false;
                
                    this.alterECLMonitoring_selected = false;
                            
        }
        
          
        public bool isStoreUCToFileSelected () {
            return this.storeUCToFile_selected ;
        }

        


        public void selectStoreUCToFile (StoreUnitControlToFile_Response val) {
            this.storeUCToFile_ = val;
            this.storeUCToFile_selected = true;
            
            
                    this.vMDStop_selected = false;
                
                    this.vMDReset_selected = false;
                
                    this.select_selected = false;
                
                    this.alterPI_selected = false;
                
                    this.initiateUCLoad_selected = false;
                
                    this.uCLoad_selected = false;
                
                    this.uCUpload_selected = false;
                
                    this.startUC_selected = false;
                
                    this.stopUC_selected = false;
                
                    this.createUC_selected = false;
                
                    this.addToUC_selected = false;
                
                    this.removeFromUC_selected = false;
                
                    this.getUCAttributes_selected = false;
                
                    this.loadUCFromFile_selected = false;
                
                    this.deleteUC_selected = false;
                
                    this.defineECL_selected = false;
                
                    this.deleteECL_selected = false;
                
                    this.addECLReference_selected = false;
                
                    this.removeECLReference_selected = false;
                
                    this.getECLAttributes_selected = false;
                
                    this.reportECLStatus_selected = false;
                
                    this.alterECLMonitoring_selected = false;
                            
        }
        
          
        public bool isDeleteUCSelected () {
            return this.deleteUC_selected ;
        }

        


        public void selectDeleteUC (DeleteUnitControl_Response val) {
            this.deleteUC_ = val;
            this.deleteUC_selected = true;
            
            
                    this.vMDStop_selected = false;
                
                    this.vMDReset_selected = false;
                
                    this.select_selected = false;
                
                    this.alterPI_selected = false;
                
                    this.initiateUCLoad_selected = false;
                
                    this.uCLoad_selected = false;
                
                    this.uCUpload_selected = false;
                
                    this.startUC_selected = false;
                
                    this.stopUC_selected = false;
                
                    this.createUC_selected = false;
                
                    this.addToUC_selected = false;
                
                    this.removeFromUC_selected = false;
                
                    this.getUCAttributes_selected = false;
                
                    this.loadUCFromFile_selected = false;
                
                    this.storeUCToFile_selected = false;
                
                    this.defineECL_selected = false;
                
                    this.deleteECL_selected = false;
                
                    this.addECLReference_selected = false;
                
                    this.removeECLReference_selected = false;
                
                    this.getECLAttributes_selected = false;
                
                    this.reportECLStatus_selected = false;
                
                    this.alterECLMonitoring_selected = false;
                            
        }
        
          
        public bool isDefineECLSelected () {
            return this.defineECL_selected ;
        }

        


        public void selectDefineECL (DefineEventConditionList_Response val) {
            this.defineECL_ = val;
            this.defineECL_selected = true;
            
            
                    this.vMDStop_selected = false;
                
                    this.vMDReset_selected = false;
                
                    this.select_selected = false;
                
                    this.alterPI_selected = false;
                
                    this.initiateUCLoad_selected = false;
                
                    this.uCLoad_selected = false;
                
                    this.uCUpload_selected = false;
                
                    this.startUC_selected = false;
                
                    this.stopUC_selected = false;
                
                    this.createUC_selected = false;
                
                    this.addToUC_selected = false;
                
                    this.removeFromUC_selected = false;
                
                    this.getUCAttributes_selected = false;
                
                    this.loadUCFromFile_selected = false;
                
                    this.storeUCToFile_selected = false;
                
                    this.deleteUC_selected = false;
                
                    this.deleteECL_selected = false;
                
                    this.addECLReference_selected = false;
                
                    this.removeECLReference_selected = false;
                
                    this.getECLAttributes_selected = false;
                
                    this.reportECLStatus_selected = false;
                
                    this.alterECLMonitoring_selected = false;
                            
        }
        
          
        public bool isDeleteECLSelected () {
            return this.deleteECL_selected ;
        }

        


        public void selectDeleteECL (DeleteEventConditionList_Response val) {
            this.deleteECL_ = val;
            this.deleteECL_selected = true;
            
            
                    this.vMDStop_selected = false;
                
                    this.vMDReset_selected = false;
                
                    this.select_selected = false;
                
                    this.alterPI_selected = false;
                
                    this.initiateUCLoad_selected = false;
                
                    this.uCLoad_selected = false;
                
                    this.uCUpload_selected = false;
                
                    this.startUC_selected = false;
                
                    this.stopUC_selected = false;
                
                    this.createUC_selected = false;
                
                    this.addToUC_selected = false;
                
                    this.removeFromUC_selected = false;
                
                    this.getUCAttributes_selected = false;
                
                    this.loadUCFromFile_selected = false;
                
                    this.storeUCToFile_selected = false;
                
                    this.deleteUC_selected = false;
                
                    this.defineECL_selected = false;
                
                    this.addECLReference_selected = false;
                
                    this.removeECLReference_selected = false;
                
                    this.getECLAttributes_selected = false;
                
                    this.reportECLStatus_selected = false;
                
                    this.alterECLMonitoring_selected = false;
                            
        }
        
          
        public bool isAddECLReferenceSelected () {
            return this.addECLReference_selected ;
        }

        


        public void selectAddECLReference (AddEventConditionListReference_Response val) {
            this.addECLReference_ = val;
            this.addECLReference_selected = true;
            
            
                    this.vMDStop_selected = false;
                
                    this.vMDReset_selected = false;
                
                    this.select_selected = false;
                
                    this.alterPI_selected = false;
                
                    this.initiateUCLoad_selected = false;
                
                    this.uCLoad_selected = false;
                
                    this.uCUpload_selected = false;
                
                    this.startUC_selected = false;
                
                    this.stopUC_selected = false;
                
                    this.createUC_selected = false;
                
                    this.addToUC_selected = false;
                
                    this.removeFromUC_selected = false;
                
                    this.getUCAttributes_selected = false;
                
                    this.loadUCFromFile_selected = false;
                
                    this.storeUCToFile_selected = false;
                
                    this.deleteUC_selected = false;
                
                    this.defineECL_selected = false;
                
                    this.deleteECL_selected = false;
                
                    this.removeECLReference_selected = false;
                
                    this.getECLAttributes_selected = false;
                
                    this.reportECLStatus_selected = false;
                
                    this.alterECLMonitoring_selected = false;
                            
        }
        
          
        public bool isRemoveECLReferenceSelected () {
            return this.removeECLReference_selected ;
        }

        


        public void selectRemoveECLReference (RemoveEventConditionListReference_Response val) {
            this.removeECLReference_ = val;
            this.removeECLReference_selected = true;
            
            
                    this.vMDStop_selected = false;
                
                    this.vMDReset_selected = false;
                
                    this.select_selected = false;
                
                    this.alterPI_selected = false;
                
                    this.initiateUCLoad_selected = false;
                
                    this.uCLoad_selected = false;
                
                    this.uCUpload_selected = false;
                
                    this.startUC_selected = false;
                
                    this.stopUC_selected = false;
                
                    this.createUC_selected = false;
                
                    this.addToUC_selected = false;
                
                    this.removeFromUC_selected = false;
                
                    this.getUCAttributes_selected = false;
                
                    this.loadUCFromFile_selected = false;
                
                    this.storeUCToFile_selected = false;
                
                    this.deleteUC_selected = false;
                
                    this.defineECL_selected = false;
                
                    this.deleteECL_selected = false;
                
                    this.addECLReference_selected = false;
                
                    this.getECLAttributes_selected = false;
                
                    this.reportECLStatus_selected = false;
                
                    this.alterECLMonitoring_selected = false;
                            
        }
        
          
        public bool isGetECLAttributesSelected () {
            return this.getECLAttributes_selected ;
        }

        


        public void selectGetECLAttributes (GetEventConditionListAttributes_Response val) {
            this.getECLAttributes_ = val;
            this.getECLAttributes_selected = true;
            
            
                    this.vMDStop_selected = false;
                
                    this.vMDReset_selected = false;
                
                    this.select_selected = false;
                
                    this.alterPI_selected = false;
                
                    this.initiateUCLoad_selected = false;
                
                    this.uCLoad_selected = false;
                
                    this.uCUpload_selected = false;
                
                    this.startUC_selected = false;
                
                    this.stopUC_selected = false;
                
                    this.createUC_selected = false;
                
                    this.addToUC_selected = false;
                
                    this.removeFromUC_selected = false;
                
                    this.getUCAttributes_selected = false;
                
                    this.loadUCFromFile_selected = false;
                
                    this.storeUCToFile_selected = false;
                
                    this.deleteUC_selected = false;
                
                    this.defineECL_selected = false;
                
                    this.deleteECL_selected = false;
                
                    this.addECLReference_selected = false;
                
                    this.removeECLReference_selected = false;
                
                    this.reportECLStatus_selected = false;
                
                    this.alterECLMonitoring_selected = false;
                            
        }
        
          
        public bool isReportECLStatusSelected () {
            return this.reportECLStatus_selected ;
        }

        


        public void selectReportECLStatus (ReportEventConditionListStatus_Response val) {
            this.reportECLStatus_ = val;
            this.reportECLStatus_selected = true;
            
            
                    this.vMDStop_selected = false;
                
                    this.vMDReset_selected = false;
                
                    this.select_selected = false;
                
                    this.alterPI_selected = false;
                
                    this.initiateUCLoad_selected = false;
                
                    this.uCLoad_selected = false;
                
                    this.uCUpload_selected = false;
                
                    this.startUC_selected = false;
                
                    this.stopUC_selected = false;
                
                    this.createUC_selected = false;
                
                    this.addToUC_selected = false;
                
                    this.removeFromUC_selected = false;
                
                    this.getUCAttributes_selected = false;
                
                    this.loadUCFromFile_selected = false;
                
                    this.storeUCToFile_selected = false;
                
                    this.deleteUC_selected = false;
                
                    this.defineECL_selected = false;
                
                    this.deleteECL_selected = false;
                
                    this.addECLReference_selected = false;
                
                    this.removeECLReference_selected = false;
                
                    this.getECLAttributes_selected = false;
                
                    this.alterECLMonitoring_selected = false;
                            
        }
        
          
        public bool isAlterECLMonitoringSelected () {
            return this.alterECLMonitoring_selected ;
        }

        


        public void selectAlterECLMonitoring (AlterEventConditionListMonitoring_Response val) {
            this.alterECLMonitoring_ = val;
            this.alterECLMonitoring_selected = true;
            
            
                    this.vMDStop_selected = false;
                
                    this.vMDReset_selected = false;
                
                    this.select_selected = false;
                
                    this.alterPI_selected = false;
                
                    this.initiateUCLoad_selected = false;
                
                    this.uCLoad_selected = false;
                
                    this.uCUpload_selected = false;
                
                    this.startUC_selected = false;
                
                    this.stopUC_selected = false;
                
                    this.createUC_selected = false;
                
                    this.addToUC_selected = false;
                
                    this.removeFromUC_selected = false;
                
                    this.getUCAttributes_selected = false;
                
                    this.loadUCFromFile_selected = false;
                
                    this.storeUCToFile_selected = false;
                
                    this.deleteUC_selected = false;
                
                    this.defineECL_selected = false;
                
                    this.deleteECL_selected = false;
                
                    this.addECLReference_selected = false;
                
                    this.removeECLReference_selected = false;
                
                    this.getECLAttributes_selected = false;
                
                    this.reportECLStatus_selected = false;
                            
        }
        
  

            public void initWithDefaults()
	    {
	    }

            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(AdditionalService_Response));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
