
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "DefineScatteredAccess_Request", IsSet = false  )]
    public class DefineScatteredAccess_Request : IASN1PreparedElement {
                    
	private ObjectName scatteredAccessName_ ;
	
        [ASN1Element ( Name = "scatteredAccessName", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public ObjectName ScatteredAccessName
        {
            get { return scatteredAccessName_; }
            set { scatteredAccessName_ = value;  }
        }
        
                
          
	private ScatteredAccessDescription scatteredAccessDescription_ ;
	
        [ASN1Element ( Name = "scatteredAccessDescription", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public ScatteredAccessDescription ScatteredAccessDescription
        {
            get { return scatteredAccessDescription_; }
            set { scatteredAccessDescription_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DefineScatteredAccess_Request));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
