
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1Choice ( Name = "GetAccessControlListAttributes_Request") ]
    public class GetAccessControlListAttributes_Request : IASN1PreparedElement {
                    
        
	private Identifier accessControlListName_ ;
        private bool  accessControlListName_selected = false ;
        
                
        
        [ASN1Element ( Name = "accessControlListName", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public Identifier AccessControlListName
        {
            get { return accessControlListName_; }
            set { selectAccessControlListName(value); }
        }
        
                
          
        
	private NullObject vMD_ ;
        private bool  vMD_selected = false ;
        
                
        
        [ASN1Null ( Name = "vMD" )]
    
        [ASN1Element ( Name = "vMD", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public NullObject VMD
        {
            get { return vMD_; }
            set { selectVMD(value); }
        }
        
                
          
        
	private NamedObjectSequenceType namedObject_ ;
        private bool  namedObject_selected = false ;
        
                
        
       [ASN1PreparedElement]
       [ASN1Sequence ( Name = "namedObject", IsSet = false  )]
       public class NamedObjectSequenceType : IASN1PreparedElement {
                        
	private ObjectClass objectClass_ ;
	
        [ASN1Element ( Name = "objectClass", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public ObjectClass ObjectClass
        {
            get { return objectClass_; }
            set { objectClass_ = value;  }
        }
        
                
          
	private ObjectName objectName_ ;
	
        [ASN1Element ( Name = "objectName", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public ObjectName ObjectName
        {
            get { return objectName_; }
            set { objectName_ = value;  }
        }
        
                
  
                
                public void initWithDefaults() {
            		
                }

            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(NamedObjectSequenceType));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

                
       }
                
        [ASN1Element ( Name = "namedObject", IsOptional =  false , HasTag =  true, Tag = 2 , HasDefaultValue =  false )  ]
    
        public NamedObjectSequenceType NamedObject
        {
            get { return namedObject_; }
            set { selectNamedObject(value); }
        }
        
                
          
        public bool isAccessControlListNameSelected () {
            return this.accessControlListName_selected ;
        }

        


        public void selectAccessControlListName (Identifier val) {
            this.accessControlListName_ = val;
            this.accessControlListName_selected = true;
            
            
                    this.vMD_selected = false;
                
                    this.namedObject_selected = false;
                            
        }
        
          
        public bool isVMDSelected () {
            return this.vMD_selected ;
        }

        
        public void selectVMD () {
            selectVMD (new NullObject());
	}
	


        public void selectVMD (NullObject val) {
            this.vMD_ = val;
            this.vMD_selected = true;
            
            
                    this.accessControlListName_selected = false;
                
                    this.namedObject_selected = false;
                            
        }
        
          
        public bool isNamedObjectSelected () {
            return this.namedObject_selected ;
        }

        


        public void selectNamedObject (NamedObjectSequenceType val) {
            this.namedObject_ = val;
            this.namedObject_selected = true;
            
            
                    this.accessControlListName_selected = false;
                
                    this.vMD_selected = false;
                            
        }
        
  

            public void initWithDefaults()
	    {
	    }

            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(GetAccessControlListAttributes_Request));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
