
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "Initiate_RequestPDU", IsSet = false  )]
    public class Initiate_RequestPDU : IASN1PreparedElement {
                    
	private Integer32 localDetailCalling_ ;
	
        private bool  localDetailCalling_present = false ;
	
        [ASN1Element ( Name = "localDetailCalling", IsOptional =  true , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public Integer32 LocalDetailCalling
        {
            get { return localDetailCalling_; }
            set { localDetailCalling_ = value; localDetailCalling_present = true;  }
        }
        
                
          
	private Integer16 proposedMaxServOutstandingCalling_ ;
	
        [ASN1Element ( Name = "proposedMaxServOutstandingCalling", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public Integer16 ProposedMaxServOutstandingCalling
        {
            get { return proposedMaxServOutstandingCalling_; }
            set { proposedMaxServOutstandingCalling_ = value;  }
        }
        
                
          
	private Integer16 proposedMaxServOutstandingCalled_ ;
	
        [ASN1Element ( Name = "proposedMaxServOutstandingCalled", IsOptional =  false , HasTag =  true, Tag = 2 , HasDefaultValue =  false )  ]
    
        public Integer16 ProposedMaxServOutstandingCalled
        {
            get { return proposedMaxServOutstandingCalled_; }
            set { proposedMaxServOutstandingCalled_ = value;  }
        }
        
                
          
	private Integer8 proposedDataStructureNestingLevel_ ;
	
        private bool  proposedDataStructureNestingLevel_present = false ;
	
        [ASN1Element ( Name = "proposedDataStructureNestingLevel", IsOptional =  true , HasTag =  true, Tag = 3 , HasDefaultValue =  false )  ]
    
        public Integer8 ProposedDataStructureNestingLevel
        {
            get { return proposedDataStructureNestingLevel_; }
            set { proposedDataStructureNestingLevel_ = value; proposedDataStructureNestingLevel_present = true;  }
        }
        
                
          
	private InitRequestDetailSequenceType initRequestDetail_ ;
	
       [ASN1PreparedElement]
       [ASN1Sequence ( Name = "initRequestDetail", IsSet = false  )]
       public class InitRequestDetailSequenceType : IASN1PreparedElement {
                        
	private Integer16 proposedVersionNumber_ ;
	
        [ASN1Element ( Name = "proposedVersionNumber", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public Integer16 ProposedVersionNumber
        {
            get { return proposedVersionNumber_; }
            set { proposedVersionNumber_ = value;  }
        }
        
                
          
	private ParameterSupportOptions proposedParameterCBB_ ;
	
        [ASN1Element ( Name = "proposedParameterCBB", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public ParameterSupportOptions ProposedParameterCBB
        {
            get { return proposedParameterCBB_; }
            set { proposedParameterCBB_ = value;  }
        }
        
                
          
	private ServiceSupportOptions servicesSupportedCalling_ ;
	
        [ASN1Element ( Name = "servicesSupportedCalling", IsOptional =  false , HasTag =  true, Tag = 2 , HasDefaultValue =  false )  ]
    
        public ServiceSupportOptions ServicesSupportedCalling
        {
            get { return servicesSupportedCalling_; }
            set { servicesSupportedCalling_ = value;  }
        }
        
                
          
	private AdditionalSupportOptions additionalSupportedCalling_ ;
	
        [ASN1Element ( Name = "additionalSupportedCalling", IsOptional =  false , HasTag =  true, Tag = 3 , HasDefaultValue =  false )  ]
    
        public AdditionalSupportOptions AdditionalSupportedCalling
        {
            get { return additionalSupportedCalling_; }
            set { additionalSupportedCalling_ = value;  }
        }
        
                
          
	private AdditionalCBBOptions additionalCbbSupportedCalling_ ;
	
        [ASN1Element ( Name = "additionalCbbSupportedCalling", IsOptional =  false , HasTag =  true, Tag = 4 , HasDefaultValue =  false )  ]
    
        public AdditionalCBBOptions AdditionalCbbSupportedCalling
        {
            get { return additionalCbbSupportedCalling_; }
            set { additionalCbbSupportedCalling_ = value;  }
        }
        
                
          
	private string privilegeClassIdentityCalling_ ;
	[ASN1String( Name = "", 
        StringType =  UniversalTags.VisibleString , IsUCS = false )]
        [ASN1Element ( Name = "privilegeClassIdentityCalling", IsOptional =  false , HasTag =  true, Tag = 5 , HasDefaultValue =  false )  ]
    
        public string PrivilegeClassIdentityCalling
        {
            get { return privilegeClassIdentityCalling_; }
            set { privilegeClassIdentityCalling_ = value;  }
        }
        
                
  
                
                public void initWithDefaults() {
            		
                }

            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(InitRequestDetailSequenceType));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

                
       }
                
        [ASN1Element ( Name = "initRequestDetail", IsOptional =  false , HasTag =  true, Tag = 4 , HasDefaultValue =  false )  ]
    
        public InitRequestDetailSequenceType InitRequestDetail
        {
            get { return initRequestDetail_; }
            set { initRequestDetail_ = value;  }
        }
        
                
  
        public bool isLocalDetailCallingPresent () {
            return this.localDetailCalling_present == true;
        }
        
        public bool isProposedDataStructureNestingLevelPresent () {
            return this.proposedDataStructureNestingLevel_present == true;
        }
        

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Initiate_RequestPDU));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
