
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace MMS_ASN1_Model {

        [ASN1Module ( Name = "ISO_9506_MMS_1", IsImplicitTags =  true  ) ]
        public class ISO_9506_MMS_1 {
        }
        
}
