
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace MMS_ASN1_Model
{


    [ASN1PreparedElement]
    [ASN1Choice(Name = "MMSpdu")]
    public class MMSpdu : IASN1PreparedElement
    {


        private Confirmed_RequestPDU confirmed_RequestPDU_;
        private bool confirmed_RequestPDU_selected = false;



        [ASN1Element(Name = "confirmed-RequestPDU", IsOptional = false, HasTag = true, Tag = 0, HasDefaultValue = false)]

        public Confirmed_RequestPDU Confirmed_RequestPDU
        {
            get { return confirmed_RequestPDU_; }
            set { selectConfirmed_RequestPDU(value); }
        }




        private Confirmed_ResponsePDU confirmed_ResponsePDU_;
        private bool confirmed_ResponsePDU_selected = false;



        [ASN1Element(Name = "confirmed-ResponsePDU", IsOptional = false, HasTag = true, Tag = 1, HasDefaultValue = false)]

        public Confirmed_ResponsePDU Confirmed_ResponsePDU
        {
            get { return confirmed_ResponsePDU_; }
            set { selectConfirmed_ResponsePDU(value); }
        }




        private Confirmed_ErrorPDU confirmed_ErrorPDU_;
        private bool confirmed_ErrorPDU_selected = false;



        [ASN1Element(Name = "confirmed-ErrorPDU", IsOptional = false, HasTag = true, Tag = 2, HasDefaultValue = false)]

        public Confirmed_ErrorPDU Confirmed_ErrorPDU
        {
            get { return confirmed_ErrorPDU_; }
            set { selectConfirmed_ErrorPDU(value); }
        }




        private Unconfirmed_PDU unconfirmed_PDU_;
        private bool unconfirmed_PDU_selected = false;



        [ASN1Element(Name = "unconfirmed-PDU", IsOptional = false, HasTag = true, Tag = 3, HasDefaultValue = false)]

        public Unconfirmed_PDU Unconfirmed_PDU
        {
            get { return unconfirmed_PDU_; }
            set { selectUnconfirmed_PDU(value); }
        }




        private RejectPDU rejectPDU_;
        private bool rejectPDU_selected = false;



        [ASN1Element(Name = "rejectPDU", IsOptional = false, HasTag = true, Tag = 4, HasDefaultValue = false)]

        public RejectPDU RejectPDU
        {
            get { return rejectPDU_; }
            set { selectRejectPDU(value); }
        }




        private Cancel_RequestPDU cancel_RequestPDU_;
        private bool cancel_RequestPDU_selected = false;



        [ASN1Element(Name = "cancel-RequestPDU", IsOptional = false, HasTag = true, Tag = 5, HasDefaultValue = false)]

        public Cancel_RequestPDU Cancel_RequestPDU
        {
            get { return cancel_RequestPDU_; }
            set { selectCancel_RequestPDU(value); }
        }




        private Cancel_ResponsePDU cancel_ResponsePDU_;
        private bool cancel_ResponsePDU_selected = false;



        [ASN1Element(Name = "cancel-ResponsePDU", IsOptional = false, HasTag = true, Tag = 6, HasDefaultValue = false)]

        public Cancel_ResponsePDU Cancel_ResponsePDU
        {
            get { return cancel_ResponsePDU_; }
            set { selectCancel_ResponsePDU(value); }
        }




        private Cancel_ErrorPDU cancel_ErrorPDU_;
        private bool cancel_ErrorPDU_selected = false;



        [ASN1Element(Name = "cancel-ErrorPDU", IsOptional = false, HasTag = true, Tag = 7, HasDefaultValue = false)]

        public Cancel_ErrorPDU Cancel_ErrorPDU
        {
            get { return cancel_ErrorPDU_; }
            set { selectCancel_ErrorPDU(value); }
        }




        private Initiate_RequestPDU initiate_RequestPDU_;
        private bool initiate_RequestPDU_selected = false;



        [ASN1Element(Name = "initiate-RequestPDU", IsOptional = false, HasTag = true, Tag = 8, HasDefaultValue = false)]

        public Initiate_RequestPDU Initiate_RequestPDU
        {
            get { return initiate_RequestPDU_; }
            set { selectInitiate_RequestPDU(value); }
        }




        private Initiate_ResponsePDU initiate_ResponsePDU_;
        private bool initiate_ResponsePDU_selected = false;



        [ASN1Element(Name = "initiate-ResponsePDU", IsOptional = false, HasTag = true, Tag = 9, HasDefaultValue = false)]

        public Initiate_ResponsePDU Initiate_ResponsePDU
        {
            get { return initiate_ResponsePDU_; }
            set { selectInitiate_ResponsePDU(value); }
        }




        private Initiate_ErrorPDU initiate_ErrorPDU_;
        private bool initiate_ErrorPDU_selected = false;



        [ASN1Element(Name = "initiate-ErrorPDU", IsOptional = false, HasTag = true, Tag = 10, HasDefaultValue = false)]

        public Initiate_ErrorPDU Initiate_ErrorPDU
        {
            get { return initiate_ErrorPDU_; }
            set { selectInitiate_ErrorPDU(value); }
        }




        private Conclude_RequestPDU conclude_RequestPDU_;
        private bool conclude_RequestPDU_selected = false;



        [ASN1Element(Name = "conclude-RequestPDU", IsOptional = false, HasTag = true, Tag = 11, HasDefaultValue = false)]

        public Conclude_RequestPDU Conclude_RequestPDU
        {
            get { return conclude_RequestPDU_; }
            set { selectConclude_RequestPDU(value); }
        }




        private Conclude_ResponsePDU conclude_ResponsePDU_;
        private bool conclude_ResponsePDU_selected = false;



        [ASN1Element(Name = "conclude-ResponsePDU", IsOptional = false, HasTag = true, Tag = 12, HasDefaultValue = false)]

        public Conclude_ResponsePDU Conclude_ResponsePDU
        {
            get { return conclude_ResponsePDU_; }
            set { selectConclude_ResponsePDU(value); }
        }




        private Conclude_ErrorPDU conclude_ErrorPDU_;
        private bool conclude_ErrorPDU_selected = false;



        [ASN1Element(Name = "conclude-ErrorPDU", IsOptional = false, HasTag = true, Tag = 13, HasDefaultValue = false)]

        public Conclude_ErrorPDU Conclude_ErrorPDU
        {
            get { return conclude_ErrorPDU_; }
            set { selectConclude_ErrorPDU(value); }
        }



        public bool isConfirmed_RequestPDUSelected()
        {
            return this.confirmed_RequestPDU_selected;
        }




        public void selectConfirmed_RequestPDU(Confirmed_RequestPDU val)
        {
            this.confirmed_RequestPDU_ = val;
            this.confirmed_RequestPDU_selected = true;


            this.confirmed_ResponsePDU_selected = false;

            this.confirmed_ErrorPDU_selected = false;

            this.unconfirmed_PDU_selected = false;

            this.rejectPDU_selected = false;

            this.cancel_RequestPDU_selected = false;

            this.cancel_ResponsePDU_selected = false;

            this.cancel_ErrorPDU_selected = false;

            this.initiate_RequestPDU_selected = false;

            this.initiate_ResponsePDU_selected = false;

            this.initiate_ErrorPDU_selected = false;

            this.conclude_RequestPDU_selected = false;

            this.conclude_ResponsePDU_selected = false;

            this.conclude_ErrorPDU_selected = false;

        }


        public bool isConfirmed_ResponsePDUSelected()
        {
            return this.confirmed_ResponsePDU_selected;
        }




        public void selectConfirmed_ResponsePDU(Confirmed_ResponsePDU val)
        {
            this.confirmed_ResponsePDU_ = val;
            this.confirmed_ResponsePDU_selected = true;


            this.confirmed_RequestPDU_selected = false;

            this.confirmed_ErrorPDU_selected = false;

            this.unconfirmed_PDU_selected = false;

            this.rejectPDU_selected = false;

            this.cancel_RequestPDU_selected = false;

            this.cancel_ResponsePDU_selected = false;

            this.cancel_ErrorPDU_selected = false;

            this.initiate_RequestPDU_selected = false;

            this.initiate_ResponsePDU_selected = false;

            this.initiate_ErrorPDU_selected = false;

            this.conclude_RequestPDU_selected = false;

            this.conclude_ResponsePDU_selected = false;

            this.conclude_ErrorPDU_selected = false;

        }


        public bool isConfirmed_ErrorPDUSelected()
        {
            return this.confirmed_ErrorPDU_selected;
        }




        public void selectConfirmed_ErrorPDU(Confirmed_ErrorPDU val)
        {
            this.confirmed_ErrorPDU_ = val;
            this.confirmed_ErrorPDU_selected = true;


            this.confirmed_RequestPDU_selected = false;

            this.confirmed_ResponsePDU_selected = false;

            this.unconfirmed_PDU_selected = false;

            this.rejectPDU_selected = false;

            this.cancel_RequestPDU_selected = false;

            this.cancel_ResponsePDU_selected = false;

            this.cancel_ErrorPDU_selected = false;

            this.initiate_RequestPDU_selected = false;

            this.initiate_ResponsePDU_selected = false;

            this.initiate_ErrorPDU_selected = false;

            this.conclude_RequestPDU_selected = false;

            this.conclude_ResponsePDU_selected = false;

            this.conclude_ErrorPDU_selected = false;

        }


        public bool isUnconfirmed_PDUSelected()
        {
            return this.unconfirmed_PDU_selected;
        }




        public void selectUnconfirmed_PDU(Unconfirmed_PDU val)
        {
            this.unconfirmed_PDU_ = val;
            this.unconfirmed_PDU_selected = true;


            this.confirmed_RequestPDU_selected = false;

            this.confirmed_ResponsePDU_selected = false;

            this.confirmed_ErrorPDU_selected = false;

            this.rejectPDU_selected = false;

            this.cancel_RequestPDU_selected = false;

            this.cancel_ResponsePDU_selected = false;

            this.cancel_ErrorPDU_selected = false;

            this.initiate_RequestPDU_selected = false;

            this.initiate_ResponsePDU_selected = false;

            this.initiate_ErrorPDU_selected = false;

            this.conclude_RequestPDU_selected = false;

            this.conclude_ResponsePDU_selected = false;

            this.conclude_ErrorPDU_selected = false;

        }


        public bool isRejectPDUSelected()
        {
            return this.rejectPDU_selected;
        }




        public void selectRejectPDU(RejectPDU val)
        {
            this.rejectPDU_ = val;
            this.rejectPDU_selected = true;


            this.confirmed_RequestPDU_selected = false;

            this.confirmed_ResponsePDU_selected = false;

            this.confirmed_ErrorPDU_selected = false;

            this.unconfirmed_PDU_selected = false;

            this.cancel_RequestPDU_selected = false;

            this.cancel_ResponsePDU_selected = false;

            this.cancel_ErrorPDU_selected = false;

            this.initiate_RequestPDU_selected = false;

            this.initiate_ResponsePDU_selected = false;

            this.initiate_ErrorPDU_selected = false;

            this.conclude_RequestPDU_selected = false;

            this.conclude_ResponsePDU_selected = false;

            this.conclude_ErrorPDU_selected = false;

        }


        public bool isCancel_RequestPDUSelected()
        {
            return this.cancel_RequestPDU_selected;
        }




        public void selectCancel_RequestPDU(Cancel_RequestPDU val)
        {
            this.cancel_RequestPDU_ = val;
            this.cancel_RequestPDU_selected = true;


            this.confirmed_RequestPDU_selected = false;

            this.confirmed_ResponsePDU_selected = false;

            this.confirmed_ErrorPDU_selected = false;

            this.unconfirmed_PDU_selected = false;

            this.rejectPDU_selected = false;

            this.cancel_ResponsePDU_selected = false;

            this.cancel_ErrorPDU_selected = false;

            this.initiate_RequestPDU_selected = false;

            this.initiate_ResponsePDU_selected = false;

            this.initiate_ErrorPDU_selected = false;

            this.conclude_RequestPDU_selected = false;

            this.conclude_ResponsePDU_selected = false;

            this.conclude_ErrorPDU_selected = false;

        }


        public bool isCancel_ResponsePDUSelected()
        {
            return this.cancel_ResponsePDU_selected;
        }




        public void selectCancel_ResponsePDU(Cancel_ResponsePDU val)
        {
            this.cancel_ResponsePDU_ = val;
            this.cancel_ResponsePDU_selected = true;


            this.confirmed_RequestPDU_selected = false;

            this.confirmed_ResponsePDU_selected = false;

            this.confirmed_ErrorPDU_selected = false;

            this.unconfirmed_PDU_selected = false;

            this.rejectPDU_selected = false;

            this.cancel_RequestPDU_selected = false;

            this.cancel_ErrorPDU_selected = false;

            this.initiate_RequestPDU_selected = false;

            this.initiate_ResponsePDU_selected = false;

            this.initiate_ErrorPDU_selected = false;

            this.conclude_RequestPDU_selected = false;

            this.conclude_ResponsePDU_selected = false;

            this.conclude_ErrorPDU_selected = false;

        }


        public bool isCancel_ErrorPDUSelected()
        {
            return this.cancel_ErrorPDU_selected;
        }




        public void selectCancel_ErrorPDU(Cancel_ErrorPDU val)
        {
            this.cancel_ErrorPDU_ = val;
            this.cancel_ErrorPDU_selected = true;


            this.confirmed_RequestPDU_selected = false;

            this.confirmed_ResponsePDU_selected = false;

            this.confirmed_ErrorPDU_selected = false;

            this.unconfirmed_PDU_selected = false;

            this.rejectPDU_selected = false;

            this.cancel_RequestPDU_selected = false;

            this.cancel_ResponsePDU_selected = false;

            this.initiate_RequestPDU_selected = false;

            this.initiate_ResponsePDU_selected = false;

            this.initiate_ErrorPDU_selected = false;

            this.conclude_RequestPDU_selected = false;

            this.conclude_ResponsePDU_selected = false;

            this.conclude_ErrorPDU_selected = false;

        }


        public bool isInitiate_RequestPDUSelected()
        {
            return this.initiate_RequestPDU_selected;
        }




        public void selectInitiate_RequestPDU(Initiate_RequestPDU val)
        {
            this.initiate_RequestPDU_ = val;
            this.initiate_RequestPDU_selected = true;


            this.confirmed_RequestPDU_selected = false;

            this.confirmed_ResponsePDU_selected = false;

            this.confirmed_ErrorPDU_selected = false;

            this.unconfirmed_PDU_selected = false;

            this.rejectPDU_selected = false;

            this.cancel_RequestPDU_selected = false;

            this.cancel_ResponsePDU_selected = false;

            this.cancel_ErrorPDU_selected = false;

            this.initiate_ResponsePDU_selected = false;

            this.initiate_ErrorPDU_selected = false;

            this.conclude_RequestPDU_selected = false;

            this.conclude_ResponsePDU_selected = false;

            this.conclude_ErrorPDU_selected = false;

        }


        public bool isInitiate_ResponsePDUSelected()
        {
            return this.initiate_ResponsePDU_selected;
        }




        public void selectInitiate_ResponsePDU(Initiate_ResponsePDU val)
        {
            this.initiate_ResponsePDU_ = val;
            this.initiate_ResponsePDU_selected = true;


            this.confirmed_RequestPDU_selected = false;

            this.confirmed_ResponsePDU_selected = false;

            this.confirmed_ErrorPDU_selected = false;

            this.unconfirmed_PDU_selected = false;

            this.rejectPDU_selected = false;

            this.cancel_RequestPDU_selected = false;

            this.cancel_ResponsePDU_selected = false;

            this.cancel_ErrorPDU_selected = false;

            this.initiate_RequestPDU_selected = false;

            this.initiate_ErrorPDU_selected = false;

            this.conclude_RequestPDU_selected = false;

            this.conclude_ResponsePDU_selected = false;

            this.conclude_ErrorPDU_selected = false;

        }


        public bool isInitiate_ErrorPDUSelected()
        {
            return this.initiate_ErrorPDU_selected;
        }




        public void selectInitiate_ErrorPDU(Initiate_ErrorPDU val)
        {
            this.initiate_ErrorPDU_ = val;
            this.initiate_ErrorPDU_selected = true;


            this.confirmed_RequestPDU_selected = false;

            this.confirmed_ResponsePDU_selected = false;

            this.confirmed_ErrorPDU_selected = false;

            this.unconfirmed_PDU_selected = false;

            this.rejectPDU_selected = false;

            this.cancel_RequestPDU_selected = false;

            this.cancel_ResponsePDU_selected = false;

            this.cancel_ErrorPDU_selected = false;

            this.initiate_RequestPDU_selected = false;

            this.initiate_ResponsePDU_selected = false;

            this.conclude_RequestPDU_selected = false;

            this.conclude_ResponsePDU_selected = false;

            this.conclude_ErrorPDU_selected = false;

        }


        public bool isConclude_RequestPDUSelected()
        {
            return this.conclude_RequestPDU_selected;
        }




        public void selectConclude_RequestPDU(Conclude_RequestPDU val)
        {
            this.conclude_RequestPDU_ = val;
            this.conclude_RequestPDU_selected = true;


            this.confirmed_RequestPDU_selected = false;

            this.confirmed_ResponsePDU_selected = false;

            this.confirmed_ErrorPDU_selected = false;

            this.unconfirmed_PDU_selected = false;

            this.rejectPDU_selected = false;

            this.cancel_RequestPDU_selected = false;

            this.cancel_ResponsePDU_selected = false;

            this.cancel_ErrorPDU_selected = false;

            this.initiate_RequestPDU_selected = false;

            this.initiate_ResponsePDU_selected = false;

            this.initiate_ErrorPDU_selected = false;

            this.conclude_ResponsePDU_selected = false;

            this.conclude_ErrorPDU_selected = false;

        }


        public bool isConclude_ResponsePDUSelected()
        {
            return this.conclude_ResponsePDU_selected;
        }




        public void selectConclude_ResponsePDU(Conclude_ResponsePDU val)
        {
            this.conclude_ResponsePDU_ = val;
            this.conclude_ResponsePDU_selected = true;


            this.confirmed_RequestPDU_selected = false;

            this.confirmed_ResponsePDU_selected = false;

            this.confirmed_ErrorPDU_selected = false;

            this.unconfirmed_PDU_selected = false;

            this.rejectPDU_selected = false;

            this.cancel_RequestPDU_selected = false;

            this.cancel_ResponsePDU_selected = false;

            this.cancel_ErrorPDU_selected = false;

            this.initiate_RequestPDU_selected = false;

            this.initiate_ResponsePDU_selected = false;

            this.initiate_ErrorPDU_selected = false;

            this.conclude_RequestPDU_selected = false;

            this.conclude_ErrorPDU_selected = false;

        }


        public bool isConclude_ErrorPDUSelected()
        {
            return this.conclude_ErrorPDU_selected;
        }




        public void selectConclude_ErrorPDU(Conclude_ErrorPDU val)
        {
            this.conclude_ErrorPDU_ = val;
            this.conclude_ErrorPDU_selected = true;


            this.confirmed_RequestPDU_selected = false;

            this.confirmed_ResponsePDU_selected = false;

            this.confirmed_ErrorPDU_selected = false;

            this.unconfirmed_PDU_selected = false;

            this.rejectPDU_selected = false;

            this.cancel_RequestPDU_selected = false;

            this.cancel_ResponsePDU_selected = false;

            this.cancel_ErrorPDU_selected = false;

            this.initiate_RequestPDU_selected = false;

            this.initiate_ResponsePDU_selected = false;

            this.initiate_ErrorPDU_selected = false;

            this.conclude_RequestPDU_selected = false;

            this.conclude_ResponsePDU_selected = false;

        }



        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(MMSpdu));
        public IASN1PreparedElementData PreparedData
        {
            get { return preparedData; }
        }

    }

}
