
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1Choice ( Name = "RemoveEventConditionListReference_Error") ]
    public class RemoveEventConditionListReference_Error : IASN1PreparedElement {
                    
        
	private ObjectName eventCondition_ ;
        private bool  eventCondition_selected = false ;
        
                
        
        [ASN1Element ( Name = "eventCondition", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public ObjectName EventCondition
        {
            get { return eventCondition_; }
            set { selectEventCondition(value); }
        }
        
                
          
        
	private ObjectName eventConditionList_ ;
        private bool  eventConditionList_selected = false ;
        
                
        
        [ASN1Element ( Name = "eventConditionList", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public ObjectName EventConditionList
        {
            get { return eventConditionList_; }
            set { selectEventConditionList(value); }
        }
        
                
          
        public bool isEventConditionSelected () {
            return this.eventCondition_selected ;
        }

        


        public void selectEventCondition (ObjectName val) {
            this.eventCondition_ = val;
            this.eventCondition_selected = true;
            
            
                    this.eventConditionList_selected = false;
                            
        }
        
          
        public bool isEventConditionListSelected () {
            return this.eventConditionList_selected ;
        }

        


        public void selectEventConditionList (ObjectName val) {
            this.eventConditionList_ = val;
            this.eventConditionList_selected = true;
            
            
                    this.eventCondition_selected = false;
                            
        }
        
  

            public void initWithDefaults()
	    {
	    }

            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(RemoveEventConditionListReference_Error));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
