
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1Choice ( Name = "Request_Detail") ]
    public class Request_Detail : IASN1PreparedElement {
                    
        
	private NullObject otherRequests_ ;
        private bool  otherRequests_selected = false ;
        
                
        
        [ASN1Null ( Name = "otherRequests" )]
    
        [ASN1Element ( Name = "otherRequests", IsOptional =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public NullObject OtherRequests
        {
            get { return otherRequests_; }
            set { selectOtherRequests(value); }
        }
        
                
          
        
	private CS_CreateProgramInvocation_Request createProgramInvocation_ ;
        private bool  createProgramInvocation_selected = false ;
        
                
        
        [ASN1Element ( Name = "createProgramInvocation", IsOptional =  false , HasTag =  true, Tag = 38 , HasDefaultValue =  false )  ]
    
        public CS_CreateProgramInvocation_Request CreateProgramInvocation
        {
            get { return createProgramInvocation_; }
            set { selectCreateProgramInvocation(value); }
        }
        
                
          
        
	private CS_Start_Request start_ ;
        private bool  start_selected = false ;
        
                
        
        [ASN1Element ( Name = "start", IsOptional =  false , HasTag =  true, Tag = 40 , HasDefaultValue =  false )  ]
    
        public CS_Start_Request Start
        {
            get { return start_; }
            set { selectStart(value); }
        }
        
                
          
        
	private CS_Resume_Request resume_ ;
        private bool  resume_selected = false ;
        
                
        
        [ASN1Element ( Name = "resume", IsOptional =  false , HasTag =  true, Tag = 42 , HasDefaultValue =  false )  ]
    
        public CS_Resume_Request Resume
        {
            get { return resume_; }
            set { selectResume(value); }
        }
        
                
          
        
	private CS_DefineEventCondition_Request defineEventCondition_ ;
        private bool  defineEventCondition_selected = false ;
        
                
        
        [ASN1Element ( Name = "defineEventCondition", IsOptional =  false , HasTag =  true, Tag = 47 , HasDefaultValue =  false )  ]
    
        public CS_DefineEventCondition_Request DefineEventCondition
        {
            get { return defineEventCondition_; }
            set { selectDefineEventCondition(value); }
        }
        
                
          
        
	private CS_AlterEventConditionMonitoring_Request alterEventConditionMonitoring_ ;
        private bool  alterEventConditionMonitoring_selected = false ;
        
                
        
        [ASN1Element ( Name = "alterEventConditionMonitoring", IsOptional =  false , HasTag =  true, Tag = 51 , HasDefaultValue =  false )  ]
    
        public CS_AlterEventConditionMonitoring_Request AlterEventConditionMonitoring
        {
            get { return alterEventConditionMonitoring_; }
            set { selectAlterEventConditionMonitoring(value); }
        }
        
                
          
        
	private CS_DefineEventEnrollment_Request defineEventEnrollment_ ;
        private bool  defineEventEnrollment_selected = false ;
        
                
        
        [ASN1Element ( Name = "defineEventEnrollment", IsOptional =  false , HasTag =  true, Tag = 57 , HasDefaultValue =  false )  ]
    
        public CS_DefineEventEnrollment_Request DefineEventEnrollment
        {
            get { return defineEventEnrollment_; }
            set { selectDefineEventEnrollment(value); }
        }
        
                
          
        
	private CS_AlterEventEnrollment_Request alterEventEnrollment_ ;
        private bool  alterEventEnrollment_selected = false ;
        
                
        
        [ASN1Element ( Name = "alterEventEnrollment", IsOptional =  false , HasTag =  true, Tag = 59 , HasDefaultValue =  false )  ]
    
        public CS_AlterEventEnrollment_Request AlterEventEnrollment
        {
            get { return alterEventEnrollment_; }
            set { selectAlterEventEnrollment(value); }
        }
        
                
          
        public bool isOtherRequestsSelected () {
            return this.otherRequests_selected ;
        }

        
        public void selectOtherRequests () {
            selectOtherRequests (new NullObject());
	}
	


        public void selectOtherRequests (NullObject val) {
            this.otherRequests_ = val;
            this.otherRequests_selected = true;
            
            
                    this.createProgramInvocation_selected = false;
                
                    this.start_selected = false;
                
                    this.resume_selected = false;
                
                    this.defineEventCondition_selected = false;
                
                    this.alterEventConditionMonitoring_selected = false;
                
                    this.defineEventEnrollment_selected = false;
                
                    this.alterEventEnrollment_selected = false;
                            
        }
        
          
        public bool isCreateProgramInvocationSelected () {
            return this.createProgramInvocation_selected ;
        }

        


        public void selectCreateProgramInvocation (CS_CreateProgramInvocation_Request val) {
            this.createProgramInvocation_ = val;
            this.createProgramInvocation_selected = true;
            
            
                    this.otherRequests_selected = false;
                
                    this.start_selected = false;
                
                    this.resume_selected = false;
                
                    this.defineEventCondition_selected = false;
                
                    this.alterEventConditionMonitoring_selected = false;
                
                    this.defineEventEnrollment_selected = false;
                
                    this.alterEventEnrollment_selected = false;
                            
        }
        
          
        public bool isStartSelected () {
            return this.start_selected ;
        }

        


        public void selectStart (CS_Start_Request val) {
            this.start_ = val;
            this.start_selected = true;
            
            
                    this.otherRequests_selected = false;
                
                    this.createProgramInvocation_selected = false;
                
                    this.resume_selected = false;
                
                    this.defineEventCondition_selected = false;
                
                    this.alterEventConditionMonitoring_selected = false;
                
                    this.defineEventEnrollment_selected = false;
                
                    this.alterEventEnrollment_selected = false;
                            
        }
        
          
        public bool isResumeSelected () {
            return this.resume_selected ;
        }

        


        public void selectResume (CS_Resume_Request val) {
            this.resume_ = val;
            this.resume_selected = true;
            
            
                    this.otherRequests_selected = false;
                
                    this.createProgramInvocation_selected = false;
                
                    this.start_selected = false;
                
                    this.defineEventCondition_selected = false;
                
                    this.alterEventConditionMonitoring_selected = false;
                
                    this.defineEventEnrollment_selected = false;
                
                    this.alterEventEnrollment_selected = false;
                            
        }
        
          
        public bool isDefineEventConditionSelected () {
            return this.defineEventCondition_selected ;
        }

        


        public void selectDefineEventCondition (CS_DefineEventCondition_Request val) {
            this.defineEventCondition_ = val;
            this.defineEventCondition_selected = true;
            
            
                    this.otherRequests_selected = false;
                
                    this.createProgramInvocation_selected = false;
                
                    this.start_selected = false;
                
                    this.resume_selected = false;
                
                    this.alterEventConditionMonitoring_selected = false;
                
                    this.defineEventEnrollment_selected = false;
                
                    this.alterEventEnrollment_selected = false;
                            
        }
        
          
        public bool isAlterEventConditionMonitoringSelected () {
            return this.alterEventConditionMonitoring_selected ;
        }

        


        public void selectAlterEventConditionMonitoring (CS_AlterEventConditionMonitoring_Request val) {
            this.alterEventConditionMonitoring_ = val;
            this.alterEventConditionMonitoring_selected = true;
            
            
                    this.otherRequests_selected = false;
                
                    this.createProgramInvocation_selected = false;
                
                    this.start_selected = false;
                
                    this.resume_selected = false;
                
                    this.defineEventCondition_selected = false;
                
                    this.defineEventEnrollment_selected = false;
                
                    this.alterEventEnrollment_selected = false;
                            
        }
        
          
        public bool isDefineEventEnrollmentSelected () {
            return this.defineEventEnrollment_selected ;
        }

        


        public void selectDefineEventEnrollment (CS_DefineEventEnrollment_Request val) {
            this.defineEventEnrollment_ = val;
            this.defineEventEnrollment_selected = true;
            
            
                    this.otherRequests_selected = false;
                
                    this.createProgramInvocation_selected = false;
                
                    this.start_selected = false;
                
                    this.resume_selected = false;
                
                    this.defineEventCondition_selected = false;
                
                    this.alterEventConditionMonitoring_selected = false;
                
                    this.alterEventEnrollment_selected = false;
                            
        }
        
          
        public bool isAlterEventEnrollmentSelected () {
            return this.alterEventEnrollment_selected ;
        }

        


        public void selectAlterEventEnrollment (CS_AlterEventEnrollment_Request val) {
            this.alterEventEnrollment_ = val;
            this.alterEventEnrollment_selected = true;
            
            
                    this.otherRequests_selected = false;
                
                    this.createProgramInvocation_selected = false;
                
                    this.start_selected = false;
                
                    this.resume_selected = false;
                
                    this.defineEventCondition_selected = false;
                
                    this.alterEventConditionMonitoring_selected = false;
                
                    this.defineEventEnrollment_selected = false;
                            
        }
        
  

            public void initWithDefaults()
	    {
	    }

            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Request_Detail));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
