
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "SCI_Information", IsSet = false  )]
    public class SCI_Information : IASN1PreparedElement {
                    
	private VMD_File partOne_ ;
	
        [ASN1Element ( Name = "partOne", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public VMD_File PartOne
        {
            get { return partOne_; }
            set { partOne_ = value;  }
        }
        
                
          
	private Service_and_Parameter_CBBs partTwo_ ;
	
        [ASN1Element ( Name = "partTwo", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public Service_and_Parameter_CBBs PartTwo
        {
            get { return partTwo_; }
            set { partTwo_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(SCI_Information));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
