
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "AlterEventEnrollment_Request", IsSet = false  )]
    public class AlterEventEnrollment_Request : IASN1PreparedElement {
                    
	private ObjectName eventEnrollmentName_ ;
	
        [ASN1Element ( Name = "eventEnrollmentName", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public ObjectName EventEnrollmentName
        {
            get { return eventEnrollmentName_; }
            set { eventEnrollmentName_ = value;  }
        }
        
                
          
	private Transitions eventConditionTransitions_ ;
	
        private bool  eventConditionTransitions_present = false ;
	
        [ASN1Element ( Name = "eventConditionTransitions", IsOptional =  true , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public Transitions EventConditionTransitions
        {
            get { return eventConditionTransitions_; }
            set { eventConditionTransitions_ = value; eventConditionTransitions_present = true;  }
        }
        
                
          
	private AlarmAckRule alarmAcknowledgmentRule_ ;
	
        private bool  alarmAcknowledgmentRule_present = false ;
	
        [ASN1Element ( Name = "alarmAcknowledgmentRule", IsOptional =  true , HasTag =  true, Tag = 2 , HasDefaultValue =  false )  ]
    
        public AlarmAckRule AlarmAcknowledgmentRule
        {
            get { return alarmAcknowledgmentRule_; }
            set { alarmAcknowledgmentRule_ = value; alarmAcknowledgmentRule_present = true;  }
        }
        
                
  
        public bool isEventConditionTransitionsPresent () {
            return this.eventConditionTransitions_present == true;
        }
        
        public bool isAlarmAcknowledgmentRulePresent () {
            return this.alarmAcknowledgmentRule_present == true;
        }
        

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(AlterEventEnrollment_Request));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
