
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "DefineEventEnrollment_Request", IsSet = false  )]
    public class DefineEventEnrollment_Request : IASN1PreparedElement {
                    
	private ObjectName eventEnrollmentName_ ;
	
        [ASN1Element ( Name = "eventEnrollmentName", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public ObjectName EventEnrollmentName
        {
            get { return eventEnrollmentName_; }
            set { eventEnrollmentName_ = value;  }
        }
        
                
          
	private ObjectName eventConditionName_ ;
	
        [ASN1Element ( Name = "eventConditionName", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public ObjectName EventConditionName
        {
            get { return eventConditionName_; }
            set { eventConditionName_ = value;  }
        }
        
                
          
	private Transitions eventConditionTransitions_ ;
	
        [ASN1Element ( Name = "eventConditionTransitions", IsOptional =  false , HasTag =  true, Tag = 2 , HasDefaultValue =  false )  ]
    
        public Transitions EventConditionTransitions
        {
            get { return eventConditionTransitions_; }
            set { eventConditionTransitions_ = value;  }
        }
        
                
          
	private AlarmAckRule alarmAcknowledgmentRule_ ;
	
        [ASN1Element ( Name = "alarmAcknowledgmentRule", IsOptional =  false , HasTag =  true, Tag = 3 , HasDefaultValue =  false )  ]
    
        public AlarmAckRule AlarmAcknowledgmentRule
        {
            get { return alarmAcknowledgmentRule_; }
            set { alarmAcknowledgmentRule_ = value;  }
        }
        
                
          
	private ObjectName eventActionName_ ;
	
        private bool  eventActionName_present = false ;
	
        [ASN1Element ( Name = "eventActionName", IsOptional =  true , HasTag =  true, Tag = 4 , HasDefaultValue =  false )  ]
    
        public ObjectName EventActionName
        {
            get { return eventActionName_; }
            set { eventActionName_ = value; eventActionName_present = true;  }
        }
        
                
          
	private ApplicationReference clientApplication_ ;
	
        private bool  clientApplication_present = false ;
	
        [ASN1Element ( Name = "clientApplication", IsOptional =  true , HasTag =  true, Tag = 5 , HasDefaultValue =  false )  ]
    
        public ApplicationReference ClientApplication
        {
            get { return clientApplication_; }
            set { clientApplication_ = value; clientApplication_present = true;  }
        }
        
                
  
        public bool isEventActionNamePresent () {
            return this.eventActionName_present == true;
        }
        
        public bool isClientApplicationPresent () {
            return this.clientApplication_present == true;
        }
        

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DefineEventEnrollment_Request));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
