
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1Choice ( Name = "EventTime") ]
    public class EventTime : IASN1PreparedElement {
                    
        
	private TimeOfDay timeOfDay_ ;
        private bool  timeOfDay_selected = false ;
        
                
        
        [ASN1Element ( Name = "timeOfDay", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public TimeOfDay TimeOfDay
        {
            get { return timeOfDay_; }
            set { selectTimeOfDay(value); }
        }
        
                
          
        
	private Unsigned32 timeSequenceIdentifier_ ;
        private bool  timeSequenceIdentifier_selected = false ;
        
                
        
        [ASN1Element ( Name = "timeSequenceIdentifier", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public Unsigned32 TimeSequenceIdentifier
        {
            get { return timeSequenceIdentifier_; }
            set { selectTimeSequenceIdentifier(value); }
        }
        
                
          
        
	private NullObject undefined_ ;
        private bool  undefined_selected = false ;
        
                
        
        [ASN1Null ( Name = "undefined" )]
    
        [ASN1Element ( Name = "undefined", IsOptional =  false , HasTag =  true, Tag = 2 , HasDefaultValue =  false )  ]
    
        public NullObject Undefined
        {
            get { return undefined_; }
            set { selectUndefined(value); }
        }
        
                
          
        public bool isTimeOfDaySelected () {
            return this.timeOfDay_selected ;
        }

        


        public void selectTimeOfDay (TimeOfDay val) {
            this.timeOfDay_ = val;
            this.timeOfDay_selected = true;
            
            
                    this.timeSequenceIdentifier_selected = false;
                
                    this.undefined_selected = false;
                            
        }
        
          
        public bool isTimeSequenceIdentifierSelected () {
            return this.timeSequenceIdentifier_selected ;
        }

        


        public void selectTimeSequenceIdentifier (Unsigned32 val) {
            this.timeSequenceIdentifier_ = val;
            this.timeSequenceIdentifier_selected = true;
            
            
                    this.timeOfDay_selected = false;
                
                    this.undefined_selected = false;
                            
        }
        
          
        public bool isUndefinedSelected () {
            return this.undefined_selected ;
        }

        
        public void selectUndefined () {
            selectUndefined (new NullObject());
	}
	


        public void selectUndefined (NullObject val) {
            this.undefined_ = val;
            this.undefined_selected = true;
            
            
                    this.timeOfDay_selected = false;
                
                    this.timeSequenceIdentifier_selected = false;
                            
        }
        
  

            public void initWithDefaults()
	    {
	    }

            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(EventTime));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
