
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace MMS_ASN1_Model {


    [ASN1PreparedElement]
    
        [ASN1Null ( Name = "InitiateDownloadSequence-Response" )]
    
    public class InitiateDownloadSequence_Response: IASN1PreparedElement {                    

            public void initWithDefaults()
	    {
	    }

            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(InitiateDownloadSequence_Response));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }



    }
            
}
