
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace MMS_ASN1_Model
{


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "SemaphoreEntry", IsSet = false)]
    public class SemaphoreEntry : IASN1PreparedElement
    {

        private byte[] entryID_;
        [ASN1OctetString(Name = "")]

        [ASN1Element(Name = "entryID", IsOptional = false, HasTag = true, Tag = 0, HasDefaultValue = false)]

        public byte[] EntryID
        {
            get { return entryID_; }
            set { entryID_ = value; }
        }



        private long entryClass_;
        [ASN1Integer(Name = "")]

        [ASN1Element(Name = "entryClass", IsOptional = false, HasTag = true, Tag = 1, HasDefaultValue = false)]

        public long EntryClass
        {
            get { return entryClass_; }
            set { entryClass_ = value; }
        }



        private ApplicationReference applicationReference_;

        [ASN1Element(Name = "applicationReference", IsOptional = false, HasTag = true, Tag = 2, HasDefaultValue = false)]

        public ApplicationReference ApplicationReference
        {
            get { return applicationReference_; }
            set { applicationReference_ = value; }
        }



        private Identifier namedToken_;

        private bool namedToken_present = false;

        [ASN1Element(Name = "namedToken", IsOptional = true, HasTag = true, Tag = 3, HasDefaultValue = false)]

        public Identifier NamedToken
        {
            get { return namedToken_; }
            set { namedToken_ = value; namedToken_present = true; }
        }



        private Priority priority_;

        [ASN1Element(Name = "priority", IsOptional = false, HasTag = true, Tag = 4, HasDefaultValue = true)]

        public Priority Priority
        {
            get { return priority_; }
            set { priority_ = value; }
        }



        private Unsigned32 remainingTimeOut_;

        private bool remainingTimeOut_present = false;

        [ASN1Element(Name = "remainingTimeOut", IsOptional = true, HasTag = true, Tag = 5, HasDefaultValue = false)]

        public Unsigned32 RemainingTimeOut
        {
            get { return remainingTimeOut_; }
            set { remainingTimeOut_ = value; remainingTimeOut_present = true; }
        }



        private bool abortOnTimeOut_;

        private bool abortOnTimeOut_present = false;
        [ASN1Boolean(Name = "")]

        [ASN1Element(Name = "abortOnTimeOut", IsOptional = true, HasTag = true, Tag = 6, HasDefaultValue = false)]

        public bool AbortOnTimeOut
        {
            get { return abortOnTimeOut_; }
            set { abortOnTimeOut_ = value; abortOnTimeOut_present = true; }
        }



        private bool relinquishIfConnectionLost_;
        [ASN1Boolean(Name = "")]

        [ASN1Element(Name = "relinquishIfConnectionLost", IsOptional = false, HasTag = true, Tag = 7, HasDefaultValue = true)]

        public bool RelinquishIfConnectionLost
        {
            get { return relinquishIfConnectionLost_; }
            set { relinquishIfConnectionLost_ = value; }
        }



        public bool isNamedTokenPresent()
        {
            return this.namedToken_present == true;
        }

        public bool isRemainingTimeOutPresent()
        {
            return this.remainingTimeOut_present == true;
        }

        public bool isAbortOnTimeOutPresent()
        {
            return this.abortOnTimeOut_present == true;
        }


        public void initWithDefaults()
        {
            Priority param_Priority =
        new Priority(64);
            Priority = param_Priority;
            bool param_RelinquishIfConnectionLost =
                    false;
            RelinquishIfConnectionLost = param_RelinquishIfConnectionLost;

        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(SemaphoreEntry));
        public IASN1PreparedElementData PreparedData
        {
            get { return preparedData; }
        }


    }

}
