
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "Service_and_Parameter_CBBs", IsSet = false  )]
    public class Service_and_Parameter_CBBs : IASN1PreparedElement {
                    
	private ServiceSupportOptions services_Client_ ;
	
        [ASN1Element ( Name = "services-Client", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public ServiceSupportOptions Services_Client
        {
            get { return services_Client_; }
            set { services_Client_ = value;  }
        }
        
                
          
	private ServiceSupportOptions services_Server_ ;
	
        [ASN1Element ( Name = "services-Server", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public ServiceSupportOptions Services_Server
        {
            get { return services_Server_; }
            set { services_Server_ = value;  }
        }
        
                
          
	private ParameterSupportOptions parameters_ ;
	
        [ASN1Element ( Name = "parameters", IsOptional =  false , HasTag =  true, Tag = 2 , HasDefaultValue =  false )  ]
    
        public ParameterSupportOptions Parameters
        {
            get { return parameters_; }
            set { parameters_ = value;  }
        }
        
                
          
	private long nest_ ;
	[ASN1Integer( Name = "" )]
    
        [ASN1Element ( Name = "nest", IsOptional =  false , HasTag =  true, Tag = 3 , HasDefaultValue =  false )  ]
    
        public long Nest
        {
            get { return nest_; }
            set { nest_ = value;  }
        }
        
                
          
	private AdditionalSupportOptions extendedServices_Client_ ;
	
        [ASN1Element ( Name = "extendedServices-Client", IsOptional =  false , HasTag =  true, Tag = 4 , HasDefaultValue =  false )  ]
    
        public AdditionalSupportOptions ExtendedServices_Client
        {
            get { return extendedServices_Client_; }
            set { extendedServices_Client_ = value;  }
        }
        
                
          
	private AdditionalSupportOptions extendedServices_Server_ ;
	
        [ASN1Element ( Name = "extendedServices-Server", IsOptional =  false , HasTag =  true, Tag = 5 , HasDefaultValue =  false )  ]
    
        public AdditionalSupportOptions ExtendedServices_Server
        {
            get { return extendedServices_Server_; }
            set { extendedServices_Server_ = value;  }
        }
        
                
          
	private AdditionalCBBOptions extendedParameters_ ;
	
        [ASN1Element ( Name = "extendedParameters", IsOptional =  false , HasTag =  true, Tag = 6 , HasDefaultValue =  false )  ]
    
        public AdditionalCBBOptions ExtendedParameters
        {
            get { return extendedParameters_; }
            set { extendedParameters_ = value;  }
        }
        
                
          
	private GeneralManagementParameters generalManagement_ ;
	
        [ASN1Element ( Name = "generalManagement", IsOptional =  false , HasTag =  true, Tag = 7 , HasDefaultValue =  false )  ]
    
        public GeneralManagementParameters GeneralManagement
        {
            get { return generalManagement_; }
            set { generalManagement_ = value;  }
        }
        
                
          
	private VMDSupportParameters vMDSupport_ ;
	
        [ASN1Element ( Name = "vMDSupport", IsOptional =  false , HasTag =  true, Tag = 8 , HasDefaultValue =  false )  ]
    
        public VMDSupportParameters VMDSupport
        {
            get { return vMDSupport_; }
            set { vMDSupport_ = value;  }
        }
        
                
          
	private DomainManagementParameters domainManagement_ ;
	
        [ASN1Element ( Name = "domainManagement", IsOptional =  false , HasTag =  true, Tag = 9 , HasDefaultValue =  false )  ]
    
        public DomainManagementParameters DomainManagement
        {
            get { return domainManagement_; }
            set { domainManagement_ = value;  }
        }
        
                
          
	private ProgramInvocationManagementParameters programInvocation_ ;
	
        [ASN1Element ( Name = "programInvocation", IsOptional =  false , HasTag =  true, Tag = 10 , HasDefaultValue =  false )  ]
    
        public ProgramInvocationManagementParameters ProgramInvocation
        {
            get { return programInvocation_; }
            set { programInvocation_ = value;  }
        }
        
                
          
	private VariableAccessParameters variableAccess_ ;
	
        [ASN1Element ( Name = "variableAccess", IsOptional =  false , HasTag =  true, Tag = 11 , HasDefaultValue =  false )  ]
    
        public VariableAccessParameters VariableAccess
        {
            get { return variableAccess_; }
            set { variableAccess_ = value;  }
        }
        
                
          
	private DataParameters dataParameters_ ;
	
        [ASN1Element ( Name = "dataParameters", IsOptional =  false , HasTag =  true, Tag = 12 , HasDefaultValue =  false )  ]
    
        public DataParameters DataParameters
        {
            get { return dataParameters_; }
            set { dataParameters_ = value;  }
        }
        
                
          
	private SemaphoreManagementParameters semaphoreManagement_ ;
	
        [ASN1Element ( Name = "semaphoreManagement", IsOptional =  false , HasTag =  true, Tag = 13 , HasDefaultValue =  false )  ]
    
        public SemaphoreManagementParameters SemaphoreManagement
        {
            get { return semaphoreManagement_; }
            set { semaphoreManagement_ = value;  }
        }
        
                
          
	private OperatorCommunicationParameters operatorCommunication_ ;
	
        [ASN1Element ( Name = "operatorCommunication", IsOptional =  false , HasTag =  true, Tag = 14 , HasDefaultValue =  false )  ]
    
        public OperatorCommunicationParameters OperatorCommunication
        {
            get { return operatorCommunication_; }
            set { operatorCommunication_ = value;  }
        }
        
                
          
	private ErrorParameters errors_ ;
	
        [ASN1Element ( Name = "errors", IsOptional =  false , HasTag =  true, Tag = 15 , HasDefaultValue =  false )  ]
    
        public ErrorParameters Errors
        {
            get { return errors_; }
            set { errors_ = value;  }
        }
        
                
          
	private FileManagementParameters fileManagement_ ;
	
        [ASN1Element ( Name = "fileManagement", IsOptional =  false , HasTag =  true, Tag = 16 , HasDefaultValue =  false )  ]
    
        public FileManagementParameters FileManagement
        {
            get { return fileManagement_; }
            set { fileManagement_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Service_and_Parameter_CBBs));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
