
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "StoreDomainContent_Request", IsSet = false  )]
    public class StoreDomainContent_Request : IASN1PreparedElement {
                    
	private Identifier domainName_ ;
	
        [ASN1Element ( Name = "domainName", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public Identifier DomainName
        {
            get { return domainName_; }
            set { domainName_ = value;  }
        }
        
                
          
	private FileName fileName_ ;
	
        [ASN1Element ( Name = "fileName", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public FileName FileName
        {
            get { return fileName_; }
            set { fileName_ = value;  }
        }
        
                
          
	private ApplicationReference thirdParty_ ;
	
        private bool  thirdParty_present = false ;
	
        [ASN1Element ( Name = "thirdParty", IsOptional =  true , HasTag =  true, Tag = 2 , HasDefaultValue =  false )  ]
    
        public ApplicationReference ThirdParty
        {
            get { return thirdParty_; }
            set { thirdParty_ = value; thirdParty_present = true;  }
        }
        
                
  
        public bool isThirdPartyPresent () {
            return this.thirdParty_present == true;
        }
        

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(StoreDomainContent_Request));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
