
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "VMDSupportParameters", IsSet = false  )]
    public class VMDSupportParameters : IASN1PreparedElement {
                    
	private MMSString localDetail_ ;
	
        [ASN1Element ( Name = "localDetail", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public MMSString LocalDetail
        {
            get { return localDetail_; }
            set { localDetail_ = value;  }
        }
        
                
          
	private MMSString extendedDerivation_ ;
	
        [ASN1Element ( Name = "extendedDerivation", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public MMSString ExtendedDerivation
        {
            get { return extendedDerivation_; }
            set { extendedDerivation_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(VMDSupportParameters));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
